import fs from 'fs';

const locs = ['fr','de','es','it','ja','ko','pl','pt','ru','tc','th','tr','uk','zh'];
const enData = JSON.parse(fs.readFileSync('src/lib/i18n/en.json', 'utf8'));
const enRelics = enData.relics || {};
const enUi = enData.ui || {};
const enUiRelicKeys = Object.keys(enUi).filter(k => k.startsWith('relics.'));

// Per-locale translations
const translations = {
    fr: {
        // relics section (11 keys) - FR already had these? Let me check
        // From committed state, FR should already have some translated
        // ui.relics.* flat keys that are still EN
        'relics.ev_title': 'Fissure de Vide exceptionnelle',
        'relics.gain_ducats': 'GAIN (D)',
        'relics.gain_plat': 'GAIN (P)',
    },
    de: {
        // relics section
        'expected_ducat': 'Erwartete Dukaten',
        'expected_platinum': 'Erwartetes Platinum',
        'no_relics_inventory': 'Keine Reliquien im Inventar',
        'no_relics_search': 'Keine Reliquien entsprechen Ihrer Suche',
        'sort_asc': 'Aufsteigend',
        'sort_desc': 'Absteigend',
        'sort_ducat': 'Nach Dukaten sortieren',
        'sort_ducat_gain': 'Dukaten-Gewinn',
        'sort_name': 'Name',
        'sort_plat': 'Nach Platinum sortieren',
        'sort_plat_gain': 'Platin-Gewinn',
        // ui.relics.* flat keys
        'relics.era': 'Era:',
        'relics.ev_title': 'Ausgezeichnete Void-Spritzer',
        'relics.sorting_by': 'Sortiere nach',
        'relics.subtitle': 'Relic-Sammlung und -Bewertung',
        'relics.refinement_intact': 'Intakt',
        'relics.refinement_exceptional': 'Ausgezeichnet',
        'relics.refinement_flawless': 'Perfekt',
        'relics.refinement_radiant': 'Strahlend',
        'relics.all': 'Alle',
        'relics.other': 'Andere',
        'relics.owned': 'Besessen:',
        'relics.target': 'Ziel',
        'relics.squad': 'Squad',
        'relics.search': 'Suche',
        'relics.sort': 'Sortieren',
        'relics.exp_ducats': 'EXP DUKATEN',
        'relics.exp_plat': 'EXP PLATIN',
        'relics.gain_ducats': 'GEWINN (D)',
        'relics.gain_plat': 'GEWINN (P)',
    },
    es: {
        'expected_ducat': 'Ducats esperados',
        'expected_platinum': 'Platino esperado',
        'no_relics_inventory': 'No hay reliquias en el inventario',
        'no_relics_search': 'Ninguna reliquia coincide con tu búsqueda',
        'sort_asc': 'Ascendente',
        'sort_desc': 'Descendente',
        'sort_ducat': 'Ordenar por Ducats',
        'sort_ducat_gain': 'Ganancia de Ducats',
        'sort_name': 'Nombre',
        'sort_plat': 'Ordenar por Platino',
        'sort_plat_gain': 'Ganancia de Platino',
        'relics.era': 'Época:',
        'relics.ev_title': 'Filadura del Vacío Excepcional',
        'relics.exp_ducats': 'DUCATS EXP',
        'relics.exp_plat': 'PLAT EXP',
        'relics.sorting_by': 'Ordenar por',
        'relics.subtitle': 'Colección y valoración de reliquias',
        'relics.refinement_intact': 'Intacto',
        'relics.refinement_exceptional': 'Excepcional',
        'relics.refinement_flawless': 'Perfecto',
        'relics.refinement_radiant': 'Radiante',
        'relics.all': 'Todos',
        'relics.other': 'Otros',
        'relics.owned': 'Poseído:',
        'relics.target': 'Objetivo',
        'relics.squad': 'Escuadrón',
        'relics.gain_ducats': 'GAN (D)',
        'relics.gain_plat': 'GAN (P)',
    },
    it: {
        'expected_ducat': 'Ducati previsti',
        'expected_platinum': 'Platinum prevista',
        'no_relics_inventory': 'Nessuna reliquia nell\'inventario',
        'no_relics_search': 'Nessuna reliquia corrisponde alla ricerca',
        'sort_asc': 'Ascendente',
        'sort_desc': 'Discendente',
        'sort_ducat': 'Ordina per Ducat',
        'sort_ducat_gain': 'Guadagno di Ducat',
        'sort_name': 'Nome',
        'sort_plat': 'Ordina per Platinum',
        'sort_plat_gain': 'Guadagno di Platinum',
        'relics.ev_title': 'Fessura Vuoto Eccezionale',
        'relics.exp_ducats': 'EXP DUCATI',
        'relics.exp_plat': 'EXP PLATINO',
        'relics.sorting_by': 'Ordina per',
        'relics.subtitle': 'Collezione di reliquie e valutazione',
        'relics.refinement_intact': 'Intatto',
        'relics.refinement_exceptional': 'Eccezionale',
        'relics.refinement_flawless': 'Perfetto',
        'relics.refinement_radiant': 'Radianza',
        'relics.all': 'Tutti',
        'relics.other': 'Altro',
        'relics.owned': 'Posseduto:',
        'relics.target': 'Bersaglio',
        'relics.squad': 'Squad',
        'relics.gain_ducats': 'VINCITA (D)',
        'relics.gain_plat': 'VINCITA (P)',
    },
    ja: {
        'expected_ducat': '期待ダクタ',
        'expected_platinum': '期待プラチナ',
        'no_relics_inventory': 'インベントリに遺物がありません',
        'no_relics_search': '検索に一致する遺物がありません',
        'sort_asc': '昇順',
        'sort_desc': '降順',
        'sort_ducat': 'ダクタで並び替え',
        'sort_ducat_gain': 'ダクタ獲得',
        'sort_name': '名前',
        'sort_plat': 'プラチナで並び替え',
        'sort_plat_gain': 'プラチナ獲得',
        'relics.ev_title': '特級虚空裂窘',
        'relics.exp_ducats': 'EXP ダクタ',
        'relics.exp_plat': 'EXP プラチナ',
        'relics.void_traces': 'ボイドトレース',
        'relics.sorting_by': '並び替え',
        'relics.subtitle': '遺物コレクションと評価',
        'relics.refinement_intact': '完全態',
        'relics.refinement_exceptional': 'エクセプショナル',
        'relics.refinement_flawless': 'フローレス',
        'relics.refinement_radiant': 'レディアント',
        'relics.all': 'すべて',
        'relics.other': 'その他',
        'relics.owned': '所持済み:',
        'relics.target': 'ターゲット',
        'relics.squad': 'スクワッド',
        'relics.gain_ducats': 'ゲイン (D)',
        'relics.gain_plat': 'ゲイン (P)',
    },
    ko: {
        'expected_ducat': '기대 덕카',
        'expected_platinum': '기대 플랫',
        'no_relics_inventory': '인벤토리에 성유물이 없습니다',
        'no_relics_search': '검색 조건에 맞는 성유물이 없습니다',
        'sort_asc': '오름차순',
        'sort_desc': '내림차순',
        'sort_ducat': '덕카별 정렬',
        'sort_ducat_gain': '덕카 획득',
        'sort_name': '이름',
        'sort_plat': '플랫별 정렬',
        'sort_plat_gain': '플랫 획득',
        'relics.ev_title': '특수한 보이드 갈라진 틈',
        'relics.exp_ducats': 'EXP 덕카',
        'relics.exp_plat': 'EXP 플랫',
        'relics.sorting_by': '정렬 방식',
        'relics.subtitle': '성유물 수집 및 가치 평가',
        'relics.refinement_intact': '완전체',
        'relics.refinement_exceptional': '특수',
        'relics.refinement_flawless': '완벽',
        'relics.refinement_radiant': '방사성',
        'relics.all': '전체',
        'relics.other': '기타',
        'relics.owned': '소유:',
        'relics.target': '대상',
        'relics.squad': '스쿼드',
        'relics.gain_ducats': '획득 (D)',
        'relics.gain_plat': '획득 (P)',
    },
    pl: {
        'expected_ducat': 'Oczekiwane dukaty',
        'expected_platinum': 'Oczekiwana platyna',
        'no_relics_inventory': 'Brak reliktów w inwentarzu',
        'no_relics_search': 'Brak reliktów spełniających kryteria',
        'sort_asc': 'Rosnąco',
        'sort_desc': 'Malejąco',
        'sort_ducat': 'Sortuj według dukatów',
        'sort_ducat_gain': 'Zysk dukatów',
        'sort_name': 'Nazwa',
        'sort_plat': 'Sortuj według platyny',
        'sort_plat_gain': 'Zysk platyny',
        'relics.ev_title': 'Wyjątkowy Zamarznięcie Próżni',
        'relics.exp_ducats': 'EXP DUCATS',
        'relics.exp_plat': 'EXP PLAT',
        'relics.sorting_by': 'Sortuj według',
        'relics.subtitle': 'Kolekcja reliktów i wycena',
        'relics.refinement_intact': 'Całkowity',
        'relics.refinement_exceptional': 'Wyjątkowy',
        'relics.refinement_flawless': 'Perfekcyjny',
        'relics.refinement_radiant': 'Promienny',
        'relics.all': 'Wszystkie',
        'relics.other': 'Inne',
        'relics.owned': 'Posiadany:',
        'relics.target': 'Cel',
        'relics.squad': 'Squad',
        'relics.gain_ducats': 'ZYSK (D)',
        'relics.gain_plat': 'ZYSK (P)',
    },
    pt: {
        'expected_ducat': 'Ducats esperados',
        'expected_platinum': 'Platina esperada',
        'no_relics_inventory': 'Nenhuma reliquia no inventário',
        'no_relics_search': 'Nenhuma reliquia corresponde à pesquisa',
        'sort_asc': 'Ascendente',
        'sort_desc': 'Descendente',
        'sort_ducat': 'Ordenar por Ducats',
        'sort_ducat_gain': 'Ganho de Ducats',
        'sort_name': 'Nome',
        'sort_plat': 'Ordenar por Platina',
        'sort_plat_gain': 'Ganho de Platina',
        'relics.ev_title': 'Fissura de Vacuidade Excepcional',
        'relics.sorting_by': 'Ordenar por',
        'relics.subtitle': 'Colecção e valorização de relics',
        'relics.refinement_intact': 'Intacto',
        'relics.refinement_exceptional': 'Excepcional',
        'relics.refinement_flawless': 'Perfeito',
        'relics.refinement_radiant': 'Radiante',
        'relics.all': 'Todos',
        'relics.other': 'Outros',
        'relics.owned': 'Possuído:',
        'relics.target': 'Alvo',
        'relics.squad': 'Esquadrião',
        'relics.gain_ducats': 'GANHO (D)',
        'relics.gain_plat': 'GANHO (P)',
    },
    ru: {
        'expected_ducat': 'Ожидаемые дукаты',
        'expected_platinum': 'Ожидаемая платина',
        'no_relics_inventory': 'Нет реликвий в инвентаре',
        'no_relics_search': 'Нет реликвий, соответствующих поиску',
        'sort_asc': 'По возрастанию',
        'sort_desc': 'По убыванию',
        'sort_ducat': 'Сортировать по дукатам',
        'sort_ducat_gain': 'Прибыль дукатов',
        'sort_name': 'Название',
        'sort_plat': 'Сортировать по платине',
        'sort_plat_gain': 'Прибыль платины',
        'relics.ev_title': 'Винятковый разлом Бездны',
        'relics.exp_ducats': 'EXP ДУКАТЫ',
        'relics.exp_plat': 'EXP ПЛАТИНА',
        'relics.sorting_by': 'Сортировать по',
        'relics.subtitle': 'Коллекция реликвий и оценка',
        'relics.refinement_intact': 'Целостный',
        'relics.refinement_exceptional': 'Исключительный',
        'relics.refinement_flawless': 'Безупречный',
        'relics.refinement_radiant': 'Лучезарный',
        'relics.all': 'Все',
        'relics.other': 'Другие',
        'relics.owned': 'В наличии:',
        'relics.target': 'Цель',
        'relics.squad': 'Отряд',
        'relics.gain_ducats': 'ПРИБЫЛЬ (D)',
        'relics.gain_plat': 'ПРИБЫЛЬ (P)',
    },
    tc: {
        'expected_ducat': '預期達卡',
        'expected_platinum': '預期白金',
        'no_relics_inventory': '背包中沒有遺物',
        'no_relics_search': '沒有遺物符合您的搜尋',
        'sort_asc': '升序',
        'sort_desc': '降序',
        'sort_ducat': '按達卡排序',
        'sort_ducat_gain': '達卡獲取',
        'sort_name': '名稱',
        'sort_plat': '按白金排序',
        'sort_plat_gain': '白金獲取',
        'relics.exp_ducats': 'EXP DUCATS',
        'relics.exp_plat': 'EXP PLATINUM',
        'relics.gain_ducats': '獲取 (D)',
        'relics.gain_plat': '獲取 (P)',
        'relics.owned': '已擁有:',
        'relics.squad': '小隊',
        'relics.target': '目標',
        'relics.sorting_by': '排序依據',
        'relics.all': '全部',
        'relics.other': '其他',
        'relics.refinement_intact': '完整',
        'relics.refinement_exceptional': '卓越',
        'relics.refinement_flawless': '完美',
        'relics.refinement_radiant': '輻射',
    },
    th: {
        'expected_ducat': 'ดุ๊กท์ที่คาดหวัง',
        'expected_platinum': 'แพลตตินัมที่คาดหวัง',
        'no_relics_inventory': 'ไม่มีเรลิกในอินเวนทอรี',
        'no_relics_search': 'ไม่มีเรลิกที่ตรงกับการค้นหา',
        'sort_asc': 'เรียงจากน้อยไปมาก',
        'sort_desc': 'เรียงจากมากไปน้อย',
        'sort_ducat': 'เรียงตามดุ๊กท์',
        'sort_ducat_gain': 'ผลตอนดุ๊กท์',
        'sort_name': 'ชื่อ',
        'sort_plat': 'เรียงตามแพลตตินัม',
        'sort_plat_gain': 'ผลตอนแพลตตินัม',
        'relics.exp_ducats': 'EXP ดุ๊กท์',
        'relics.exp_plat': 'EXP แพลตตินัม',
        'relics.gain_ducats': 'ได้รับ (D)',
        'relics.gain_plat': 'ได้รับ (P)',
        'relics.owned': 'มีเจ้าของ:',
        'relics.squad': 'ทีม',
        'relics.target': 'เป้าหมาย',
        'relics.sorting_by': 'เรียงตาม',
        'relics.all': 'ทั้งหมด',
        'relics.other': 'อื่นๆ',
        'relics.refinement_intact': 'สมบูรณ์',
        'relics.refinement_exceptional': 'เหนือกว่า',
        'relics.refinement_flawless': 'สมบูรณ์',
        'relics.refinement_radiant': 'รัศี',
    },
    tr: {
        'expected_ducat': 'Beklenen Dukat',
        'expected_platinum': 'Beklenen Platinum',
        'no_relics_inventory': 'Envanterde ilâhlik yok',
        'no_relics_search': 'Aramanıza uygun ilâhlik yok',
        'sort_asc': 'Artan',
        'sort_desc': 'Azalan',
        'sort_ducat': 'Dukata göre sırala',
        'sort_ducat_gain': 'Dukat kazancı',
        'sort_name': 'İsim',
        'sort_plat': 'Platinaya göre sırala',
        'sort_plat_gain': 'Platinum kazancı',
        'relics.exp_ducats': 'EXP DUKAT',
        'relics.exp_plat': 'EXP PLATINUM',
        'relics.gain_ducats': 'KAZAN (D)',
        'relics.gain_plat': 'KAZAN (P)',
        'relics.owned': 'Sahip:',
        'relics.squad': 'Taban',
        'relics.target': 'Hedef',
        'relics.sorting_by': 'Sırala',
        'relics.all': 'Tümü',
        'relics.other': 'Diğer',
        'relics.refinement_intact': 'Bütün',
        'relics.refinement_exceptional': 'Özel',
        'relics.refinement_flawless': 'Kusursuz',
        'relics.refinement_radiant': 'Radyant',
    },
    uk: {
        'expected_ducat': 'Очікувані дукати',
        'expected_platinum': 'Очікувана платина',
        'no_relics_inventory': 'Немає реліквій у інвентарі',
        'no_relics_search': 'Немає реліквій, що відповідають пошуку',
        'sort_asc': 'За зростанням',
        'sort_desc': 'За спаданням',
        'sort_ducat': 'Сортувати за дукатами',
        'sort_ducat_gain': 'Надходження дукатів',
        'sort_name': 'Назва',
        'sort_plat': 'Сортувати за платиною',
        'sort_plat_gain': 'Надходження платини',
        'relics.exp_ducats': 'EXP ДУКАТИ',
        'relics.exp_plat': 'EXP ПЛАТИНА',
        'relics.gain_ducats': 'НАДХОДЖЕННЯ (D)',
        'relics.gain_plat': 'НАДХОДЖЕННЯ (P)',
        'relics.owned': 'Мається:',
        'relics.target': 'Ціль',
        'relics.squad': 'Рота',
        'relics.sorting_by': 'Сортувати за',
        'relics.all': 'Усі',
        'relics.other': 'Інші',
        'relics.refinement_intact': 'Цілий',
        'relics.refinement_exceptional': 'Винятковий',
        'relics.refinement_flawless': 'Бездоганний',
        'relics.refinement_radiant': 'Промінючий',
    },
    zh: {
        'expected_ducat': '期待达卡',
        'expected_platinum': '期待白金',
        'no_relics_inventory': '背包中没有遗物',
        'no_relics_search': '没有遗物符合您的搜索',
        'sort_asc': '升序',
        'sort_desc': '降序',
        'sort_ducat': '按达卡排序',
        'sort_ducat_gain': '达卡获取',
        'sort_name': '名称',
        'sort_plat': '按白金排序',
        'sort_plat_gain': '白金获取',
        'relics.exp_ducats': 'EXP DUCATS',
        'relics.exp_plat': 'EXP PLATINUM',
        'relics.gain_ducats': '获取 (D)',
        'relics.gain_plat': '获取 (P)',
        'relics.owned': '已拥有:',
        'relics.target': '目标',
        'relics.squad': '小队',
        'relics.sorting_by': '排序方式',
        'relics.all': '全部',
        'relics.other': '其他',
        'relics.refinement_intact': '完整',
        'relics.refinement_exceptional': '卓越',
        'relics.refinement_flawless': '完美',
        'relics.refinement_radiant': '辐射',
    },
};

// Keys that are format strings / placeholders - do NOT translate
const DONT_TRANSLATE = [
    'bp_close',       // "BP)" - format string suffix
    'era_label',      // "{era}" - placeholder
    'platinum',       // "{plat}p" - format string
];

for (const loc of locs) {
    const filePath = `src/lib/i18n/${loc}.json`;
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    const trans = translations[loc] || {};
    let changes = [];
    
    // Fix relics section (keys without 'relics.' prefix)
    if (data.relics) {
        for (const [key, enVal] of Object.entries(enRelics)) {
            const flatKey = key;  // e.g., "expected_ducat"
            if (!(flatKey in trans)) continue;
            if (data.relics[key] === enVal) {
                data.relics[key] = trans[flatKey];
                changes.push(`relics.${key} = "${trans[flatKey]}"`);
            }
        }
    }
    
    // Fix ui.relics.* flat keys (keys WITH 'relics.' prefix)
    if (data.ui) {
        for (const [key, enVal] of Object.entries(enUi)) {
            if (!key.startsWith('relics.')) continue;
            // Skip format string keys
            const shortKey = key.substring(8); // remove "relics." prefix
            if (DONT_TRANSLATE.includes(shortKey)) continue;
            if (!(key in trans)) continue;
            if (data.ui[key] === enVal) {
                data.ui[key] = trans[key];
                changes.push(`${key} = "${trans[key]}"`);
            }
        }
    }
    
    if (changes.length > 0) {
        fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n');
        console.log(`${loc}: ${changes.length} fixes`);
        changes.forEach(c => console.log(`  ${c}`));
    } else {
        console.log(`${loc}: already clean`);
    }
}

console.log('\nDone!');
