#!/usr/bin/env python3
"""
FIX descendia_mission_type_desc_* across all 13 locales.
Many still had the 'Fill a Crucible using two elemental Amphors.' placeholder
or truncated text ('Boss...', 'Defend a target from...'). EN source itself has
wrong/placeholder values for some keys; FR has the correct meaning. Use correct
meaning per key, translated per locale. No emdashes.
"""
import json, os
os.chdir('/home/emre/Downloads/cephalon-kronos')
LOCALES = ['de','es','it','ja','ko','pl','pt','ru','tc','th','tr','uk','zh']

def load_json(p):
    with open(p, encoding='utf-8') as f:
        return json.load(f)

def save_locale(lo, data):
    with open(f'src/lib/i18n/{lo}.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent='\t')

locale_files = {lo: load_json(f'src/lib/i18n/{lo}.json') for lo in LOCALES}

# Correct meanings per key, translated into all 13 locales
D = {
 'dt_alchemy': {  # Fill a Crucible using two elemental Amphors.
   'de': 'Fülle einen Schmelztiegel mit zwei elementaren Amphoren.',
   'es': 'Llena un Crisol con dos Ánforas elementales.',
   'it': 'Riempi un Crogiuolo con due Anfore elementali.',
   'ja': '2つの属性アンフォラで坩堝を満たせ。',
   'ko': '두 개의 원소 암포라로 도가니를 채우세요.',
   'pl': 'Napełnij Tygiel dwiema żywiołowymi amforami.',
   'pt': 'Encha um Crisol com duas Ânforas elementais.',
   'ru': 'Заполните Тигель двумя стихийными амфорами.',
   'tc': '用兩個屬性安芙拉裝滿坩堝。',
   'th': 'เติมแอมฟอร่าธาตุสองอันลงในครูซิเบิล',
   'tr': 'İki elementli Amphor ile bir potayı doldur.',
   'uk': 'Заповніть Тигель двома стихійними амфорами.',
   'zh': '用两个属性安芙拉装满坩埚。'},
 'dt_boss': {  # Boss fight encounter.
   'de': 'Bosskampf-Begegnung.',
   'es': 'Encuentro de jefe.',
   'it': 'Incontro con un boss.',
   'ja': 'ボス戦。',
   'ko': '보스 전투.',
   'pl': 'Walka z bossem.',
   'pt': 'Encontro de chefe.',
   'ru': 'Битва с боссом.',
   'tc': '首領戰。',
   'th': 'การเผชิญหน้าบอส',
   'tr': 'Boss dövüşü karşılaşması.',
   'uk': 'Битва з босом.',
   'zh': '首领战。'},
 'dt_break_targets': {  # Destroy floating hologlobes.
   'de': 'Zerstöre schwebende Hologloben.',
   'es': 'Destruye los Hologlobos flotantes.',
   'it': 'Distruggi gli Hologlobi fluttuanti.',
   'ja': '浮遊するホログローブを破壊せよ。',
   'ko': '떠다니는 홀로글로브를 파괴하세요.',
   'pl': 'Zniszcz lewitujące Hologloby.',
   'pt': 'Destrua os Hologlobos flutuantes.',
   'ru': 'Уничтожьте парящие Гологлобы.',
   'tc': '摧毀漂浮的全像球。',
   'th': 'ทำลายโฮโลโกลบที่ลอยอยู่',
   'tr': 'Süzülen Hologlobe\'ları yok et.',
   'uk': 'Знищіть парячі Гологлоби.',
   'zh': '摧毁漂浮的全像球。'},
 'dt_capture': {  # Capture the target.
   'de': 'Fange das Ziel.',
   'es': 'Captura al objetivo.',
   'it': 'Cattura il bersaglio.',
   'ja': '目標を捕獲せよ。',
   'ko': '목표를 포획하세요.',
   'pl': 'Schwytać cel.',
   'pt': 'Capture o alvo.',
   'ru': 'Захватите цель.',
   'tc': '捕獲目標。',
   'th': 'จับเป้าหมาย',
   'tr': 'Hedefi yakala.',
   'uk': 'Захопіть ціль.',
   'zh': '捕获目标。'},
 'dt_collection': {  # Collect Vitoplast.
   'de': 'Sammle Vitoplast.',
   'es': 'Recoge Vitoplasto.',
   'it': 'Raccogli Vitoplast.',
   'ja': 'バイトプラストを収集せよ。',
   'ko': '바이토플라스트를 수집하세요.',
   'pl': 'Zbierz Witoplast.',
   'pt': 'Colete Vitoplast.',
   'ru': 'Соберите Витопласт.',
   'tc': '收集維托塑膠。',
   'th': 'เก็บไวโทพลาสต์',
   'tr': 'Vitoplast topla.',
   'uk': 'Зберіть Вітопласт.',
   'zh': '收集维托塑胶。'},
 'dt_defense': {  # Defend a target from waves of enemies.
   'de': 'Verteidige ein Ziel gegen Wellen von Feinden.',
   'es': 'Defiende un objetivo de oleadas de enemigos.',
   'it': 'Difendi un bersaglio dalle ondate nemiche.',
   'ja': '押し寄せる敵の波から目標を守れ。',
   'ko': '밀려오는 적의 파도로부터 목표를 지키세요.',
   'pl': 'Broń celu przed falami wrogów.',
   'pt': 'Defenda um alvo das ondas de inimigos.',
   'ru': 'Защищайте цель от волн врагов.',
   'tc': '抵禦敵人波次，保衛目標。',
   'th': 'ปกป้องเป้าหมายจากคลื่นศัตรู',
   'tr': 'Hedefi düşman dalgalarına karşı koru.',
   'uk': 'Захищайте ціль від хвиль ворогів.',
   'zh': '抵御敌人波次，保卫目标。'},
 'dt_excavation': {  # Protect Excavators and keep them powered with Power Cells.
   'de': 'Schütze die Excavatoren und halte sie mit Energiezellen am Laufen.',
   'es': 'Protege las Excavadoras y mantenlas con Células de Energía.',
   'it': 'Proteggi gli Scavatori e tienili carichi con Cellule di Energia.',
   'ja': '掘削機を守り、パワーセルで稼働させ続けろ。',
   'ko': '굴착기를 보호하고 파워 셀로 전력을 유지하세요.',
   'pl': 'Chroń Wykrywacze i zasilaj je Komórkami Energii.',
   'pt': 'Proteja as Escavadeiras e mantenha-as com Células de Energia.',
   'ru': 'Защищайте Экскаваторы и питайте их Энергоячейками.',
   'tc': '保護挖掘機並用能量電池維持運作。',
   'th': 'ปกป้องเครื่องขุดและเติมพลังงานด้วยเซลล์พลังงาน',
   'tr': 'Kazıcıları koru ve Güç Hücreleriyle çalışır tut.',
   'uk': 'Захищайте Екскаватори та живіть їх Енергочарунками.',
   'zh': '保护挖掘机并用能量电池维持运转。'},
 'dt_exterminate': {  # Kill a specific number of enemies.
   'de': 'Töte eine bestimmte Anzahl von Feinden.',
   'es': 'Elimina un número específico de enemigos.',
   'it': 'Uccidi un numero specifico di nemici.',
   'ja': '指定数の敵を倒せ。',
   'ko': '정해진 수의 적을 처치하세요.',
   'pl': 'Zabij określoną liczbę wrogów.',
   'pt': 'Elimine um número específico de inimigos.',
   'ru': 'Убейте определённое количество врагов.',
   'tc': '消滅指定數量的敵人。',
   'th': 'ฆ่าศัตรูตามจำนวนที่กำหนด',
   'tr': 'Belirli sayıda düşman öldür.',
   'uk': 'Знищіть певну кількість ворогів.',
   'zh': '消灭指定数量的敌人。'},
 'dt_infested_salvage': {  # Cleanse nodes of Infestation to power a Vaporizer.
   'de': 'Befreie Knoten von der Infestation, um einen Vaporizer zu betreiben.',
   'es': 'Limpia los nodos de la Infestación para alimentar un Vaporizador.',
   'it': 'Pulisci i nodi dall\'Infestazione per alimentare un Vaporizzatore.',
   'ja': '感染したノードを浄化してベポライザーを稼働させろ。',
   'ko': '감염된 노드를 정화하여 베이퍼라이저에 전력을 공급하세요.',
   'pl': 'Oczyść węzły z Infestacji, aby zasilić Waporyzator.',
   'pt': 'Limpe os nós da Infestação para alimentar um Vaporizador.',
   'ru': 'Очистите узлы от Заражения, чтобы питать Вапоризатор.',
   'tc': '淨化感染節點以驅動汽化器。',
   'th': 'ชำระล้างโหนดอินเฟสเตชันเพื่อจ่ายพลังให้เวโปไรเซอร์',
   'tr': 'Bir Vaporizer\'ı çalıştırmak için düğümleri İnfestasyon\'dan arındır.',
   'uk': 'Очистіть вузли від Зараження, щоб живити Вапоризатор.',
   'zh': '净化感染节点以驱动汽化器。'},
 'dt_interception': {  # Defend and capture intercept points.
   'de': 'Verteidige und erobere Intercept-Punkte.',
   'es': 'Defiende y captura los puntos de intercepción.',
   'it': 'Difendi e cattura i punti di intercettazione.',
   'ja': 'インターセプト地点を防衛・占領せよ。',
   'ko': '차단 지점을 방어하고 점령하세요.',
   'pl': 'Broń i przejmuj punkty przechwytu.',
   'pt': 'Defenda e capture os pontos de interceptação.',
   'ru': 'Защищайте и захватывайте точки перехвата.',
   'tc': '防守並佔領攔截點。',
   'th': 'ปกป้องและยึดจุดสกัดกั้น',
   'tr': 'Kesme noktalarını savun ve ele geçir.',
   'uk': 'Захищайте та захоплюйте точки перехоплення.',
   'zh': '防守并占领拦截点。'},
 'dt_loot': {  # Loot containers within time limit.
   'de': 'Plündere Container innerhalb des Zeitlimits.',
   'es': 'Saquea contenedores dentro del límite de tiempo.',
   'it': 'Saccheggia i contenitori entro il limite di tempo.',
   'ja': '制限時間内にコンテナを略奪せよ。',
   'ko': '시간 제한 안에 컨테이너를 약탈하세요.',
   'pl': 'Zrabuj kontenery w czasie.',
   'pt': 'Saqueie contêineres dentro do limite de tempo.',
   'ru': 'Разграбите контейнеры за отведённое время.',
   'tc': '在時間限制內掠奪容器。',
   'th': 'ปล้นภาชนะภายในเวลาที่กำหนด',
   'tr': 'Süre sınırı içinde konteynerleri yağmala.',
   'uk': 'Пограбуйте контейнери за відведений час.',
   'zh': '在时间限制内掠夺容器。'},
 'dt_loot_creatures': {  # Kill loot creatures before they escape.
   'de': 'Töte Beute-Kreaturen, bevor sie entkommen.',
   'es': 'Elimina a las criaturas de botín antes de que escapen.',
   'it': 'Uccidi le creature da bottino prima che scappino.',
   'ja': '獲物クリーチャーが逃げる前に倒せ。',
   'ko': '약탈 생물이 도망치기 전에 처치하세요.',
   'pl': 'Zabij stwory z łupami, zanim uciekną.',
   'pt': 'Elimine as criaturas de saque antes que fujam.',
   'ru': 'Убейте существ с добычей, пока они не сбежали.',
   'tc': '在掠奪生物逃跑前將其消滅。',
   'th': 'ฆ่าสิ่งมีชีวิตที่ขนของก่อนมันหนี',
   'tr': 'Yağma yaratıkları kaçmadan öldür.',
   'uk': 'Знищіть істот із здобиччю, поки вони не втекли.',
   'zh': '在掠夺生物逃跑前将其消灭。'},
 'dt_mimics': {  # Loot storage containers within time limit - beware of mimics.
   'de': 'Plündere Container innerhalb des Zeitlimits - Vorsicht vor Mimics.',
   'es': 'Saquea contenedores dentro del límite de tiempo - cuidado con los mímics.',
   'it': 'Saccheggia i contenitori entro il limite di tempo - attenzione ai mimici.',
   'ja': '制限時間内にコンテナを略奪せよ - ミミックに注意。',
   'ko': '시간 제한 안에 컨테이너를 약탈하세요 - 미믹을 조심하세요.',
   'pl': 'Zrabuj kontenery w czasie - uważaj na mimiki.',
   'pt': 'Saqueie contêineres dentro do limite de tempo - cuidado com os mímics.',
   'ru': 'Разграбите контейнеры за время - остерегайтесь мимиков.',
   'tc': '在時間限制內掠奪容器 - 小心模仿者。',
   'th': 'ปล้นภาชนะภายในเวลาที่กำหนด - ระวังมิมิก',
   'tr': 'Süre sınırı içinde konteynerleri yağmala - mimiklere dikkat.',
   'uk': 'Пограбуйте контейнери за час - остерігайтеся міміків.',
   'zh': '在时间限制内掠夺容器 - 小心模仿者。'},
 'dt_netracells': {  # Kill marked Necramites that periodically spawn.
   'de': 'Töte markierte Necramiten, die regelmäßig erscheinen.',
   'es': 'Elimina a los Necramitas marcados que aparecen periódicamente.',
   'it': 'Uccidi i Necramiti marcati che compaiono periodicamente.',
   'ja': '定期的に出現するマークされたネクラマイトを倒せ。',
   'ko': '주기적으로 나타나는 표시된 네크라마이트를 처치하세요.',
   'pl': 'Zabij oznaczone Necramity, które pojawiają się okresowo.',
   'pt': 'Elimine os Necramitas marcados que surgem periodicamente.',
   'ru': 'Убейте отмеченных Некрамитов, которые периодически появляются.',
   'tc': '消滅定期出現的標記亡骸士兵。',
   'th': 'ฆ่าเนคราไมต์ที่ถูกทำเครื่องหมายซึ่งเกิดเป็นระยะ',
   'tr': 'Periyodik olarak beliren işaretli Necramite\'ları öldür.',
   'uk': 'Знищіть позначених Некрамітів, які періодично з\'являються.',
   'zh': '消灭定期出现的标记亡骸士兵。'},
 'dt_presure_gauge': {  # Fill a Conversion Progress gauge.
   'de': 'Fülle eine Umwandlungsfortschritts-Anzeige.',
   'es': 'Llena un medidor de Progreso de Conversión.',
   'it': 'Riempi un indicatore di Progresso di Conversione.',
   'ja': '変換進行ゲージを満たせ。',
   'ko': '변환 진행 게이지를 채우세요.',
   'pl': 'Napełnij wskaźnik Postępu Konwersji.',
   'pt': 'Encha um medidor de Progresso de Conversão.',
   'ru': 'Заполните шкалу прогресса Преобразования.',
   'tc': '填滿轉換進度條。',
   'th': 'เติมเกจความคืบหน้าการแปลง',
   'tr': 'Dönüşüm İlerleme göstergesini doldur.',
   'uk': 'Заповніть шкалу прогресу Перетворення.',
   'zh': '填满转换进度条。'},
 'dt_protoframe': {  # Special protoframe encounter - boss or sanctuary.
   'de': 'Besondere Protoframe-Begegnung - Boss oder Heiligtum.',
   'es': 'Encuentro especial de Protoframe - jefe o santuario.',
   'it': 'Incontro speciale con Protoframe - boss o santuario.',
   'ja': '特殊なプロトフレーム戦 - ボスまたは聖域。',
   'ko': '특수 프로토프레임 전투 - 보스 또는 성소.',
   'pl': 'Specjalne spotkanie z Protoframe - boss lub sanktuarium.',
   'pt': 'Encontro especial de Protoframe - chefe ou santuário.',
   'ru': 'Особая встреча с Протофреймом - босс или святилище.',
   'tc': '特殊原型戰甲遭遇 - 首領或聖殿。',
   'th': 'การเผชิญหน้าโปรโตเฟรมพิเศษ - บอสหรือสถานศักดิ์สิทธิ์',
   'tr': 'Özel protoframe karşılaşması - boss veya sığınak.',
   'uk': 'Особлива зустріч з Протофреймом - бос або святилище.',
   'zh': '特殊原型战甲遭遇 - 首领或圣殿。'},
 'dt_race': {  # Race through gates in order within time limit.
   'de': 'Renne in der richtigen Reihenfolge durch die Tore innerhalb des Zeitlimits.',
   'es': 'Corre por las puertas en orden dentro del límite de tiempo.',
   'it': 'Corri attraverso i cancelli in ordine entro il limite di tempo.',
   'ja': '制限時間内にゲートを順番に通過せよ。',
   'ko': '시간 제한 안에 게이트를 순서대로 통과하세요.',
   'pl': 'Przejedź przez bramy w kolejności w czasie.',
   'pt': 'Corra pelos portões em ordem dentro do limite de tempo.',
   'ru': 'Проезжайте через врата по порядку за отведённое время.',
   'tc': '在時間限制內依序通過閘門。',
   'th': 'วิ่งผ่านประตูตามลำดับภายในเวลาที่กำหนด',
   'tr': 'Zaman sınırı içinde kapılardan sırayla geç.',
   'uk': 'Проїжджайте крізь ворота по порядку за відведений час.',
   'zh': '在时间限制内依序通过闸门。'},
 'dt_sabotage_defense': {  # Destroy Infested Tumors to eliminate their Hives.
   'de': 'Zerstöre Infested-Tumore, um ihre Hives zu eliminieren.',
   'es': 'Destruye los Tumores Infestados para eliminar sus Colmenas.',
   'it': 'Distruggi i Tumori Infestati per eliminare i loro Alveari.',
   'ja': '感染腫瘍を破壊してハイブを排除せよ。',
   'ko': '감염 종양을 파괴하여 하이브를 제거하세요.',
   'pl': 'Zniszcz Guzy Infestacji, aby wyeliminować ich Ule.',
   'pt': 'Destrua os Tumores Infestados para eliminar suas Colmeias.',
   'ru': 'Уничтожьте Опухоли Заражения, чтобы устранить их Ульи.',
   'tc': '摧毀感染腫瘤以消滅其蜂巢。',
   'th': 'ทำลายเนื้องอกอินเฟสเตชันเพื่อกำจัดรัง',
   'tr': 'Kovanlarını yok etmek için Infested Tümörlerini yok et.',
   'uk': 'Знищіть Пухлини Зараження, щоб усунути їхні Вулики.',
   'zh': '摧毁感染肿瘤以消灭其蜂巢。'},
 'dt_sabotage_hive': {  # Destroy Infested Tumors to eliminate their Hives.
   'de': 'Zerstöre Infested-Tumore, um ihre Hives zu eliminieren.',
   'es': 'Destruye los Tumores Infestados para eliminar sus Colmenas.',
   'it': 'Distruggi i Tumori Infestati per eliminare i loro Alveari.',
   'ja': '感染腫瘍を破壊してハイブを排除せよ。',
   'ko': '감염 종양을 파괴하여 하이브를 제거하세요.',
   'pl': 'Zniszcz Guzy Infestacji, aby wyeliminować ich Ule.',
   'pt': 'Destrua os Tumores Infestados para eliminar suas Colmeias.',
   'ru': 'Уничтожьте Опухоли Заражения, чтобы устранить их Ульи.',
   'tc': '摧毀感染腫瘤以消滅其蜂巢。',
   'th': 'ทำลายเนื้องอกอินเฟสเตชันเพื่อกำจัดรัง',
   'tr': 'Kovanlarını yok etmek için Infested Tümörlerini yok et.',
   'uk': 'Знищіть Пухлини Зараження, щоб усунути їхні Вулики.',
   'zh': '摧毁感染肿瘤以消灭其蜂巢。'},
 'dt_shrine_defense': {  # Keep enemies out of a point, deposit offerings to spawn a boss.
   'de': 'Halte Feinde von einem Punkt fern und bringe Opfergaben, um einen Boss erscheinen zu lassen.',
   'es': 'Mantén a los enemigos fuera de un punto y deposita ofrendas para invocar a un jefe.',
   'it': 'Tieni i nemici lontani da un punto e deposita offerte per evocare un boss.',
   'ja': '敵をポイントから遠ざけ、奉納品を捧げてボスを呼び出せ。',
   'ko': '적을 지점에서 멀리하고 공물을 바쳐 보스를 소환하세요.',
   'pl': 'Trzymaj wrogów z dala od punktu i złóż ofiary, aby przywołać bossa.',
   'pt': 'Mantenha os inimigos longe de um ponto e deposite oferendas para invocar um chefe.',
   'ru': 'Не подпускайте врагов к точке и приносите подношения, чтобы призвать босса.',
   'tc': '阻止敵人靠近據點，獻上祭品以召喚首領。',
   'th': 'กันศัตรูออกจากจุดและวางเครื่องบูชาเพื่อเรียกบอส',
   'tr': 'Düşmanları noktadan uzak tut ve boss çağırmak için adakları bırak.',
   'uk': 'Не підпускайте ворогів до точки та кладіть підношення, щоб прикликати боса.',
   'zh': '阻止敌人靠近据点，献上祭品以召唤首领。'},
 'dt_unique': {  # Unique mission objective.
   'de': 'Einzigartiges Missionsziel.',
   'es': 'Objetivo de misión único.',
   'it': 'Obiettivo di missione unico.',
   'ja': '特別なミッション目標。',
   'ko': '특별한 임무 목표.',
   'pl': 'Unikalny cel misji.',
   'pt': 'Objetivo de missão único.',
   'ru': 'Уникальная цель миссии.',
   'tc': '特殊任務目標。',
   'th': 'วัตถุประสงค์ภารกิจพิเศษ',
   'tr': 'Benzersiz görev hedefi.',
   'uk': 'Унікальна ціль місії.',
   'zh': '特殊任务目标。'},
}

BAD = {
    'Fill a Crucible using two elemental Amphors.',
    'Boss...',
    'Defend a target from...',
    'Fill a Crucible using two elemental Amphors',
}

applied = 0
for key, trans in D.items():
    fk = f'ui.dashboard.descendia_mission_type_desc_{key}'
    for lo, val in trans.items():
        cur = locale_files[lo]['ui'].get(fk)
        if cur in BAD or (isinstance(cur, str) and (cur.endswith('...') or cur.startswith('Fill a Crucible'))):
            locale_files[lo]['ui'][fk] = val
            applied += 1

print(f"Applied {applied} desc fixes")
for lo in LOCALES:
    save_locale(lo, locale_files[lo])
print("Saved.")
