#!/usr/bin/env python3
"""
Step 1: Write the translations_batch4.json with proper translations for all 33 remaining entries.
Step 2: Merge into T.
Step 3: Fix apply_translations_v2.py to use flat key format.
Step 4: Apply translations.
Step 5: Build + verify.

FR translations (from locale file):
- Fill a Crucible using two elemental Amphors. -> Terminez la mission d'Alchimie.
- Destroy floating hologlobes. -> Détruisez les Hologlobes pour réduire la santé des ennemis.
- Capture the target. -> Capturez la cible.
- Collect Vitoplast. -> Vainquez des ennemis pour faire apparaître une Inondation du Néant, puis collectez les récompenses.
- Protect Excavators and keep them powered with Power Cells. -> Les ennemis infligent des dégâts massifs.
- Kill a specific number of enemies. -> Exterminez tous les ennemis.
- Cleanse nodes of Infestation to power a Vaporizer. -> Récupération infestée - protégez l'antitoxine.
- Defend and capture intercept points. -> Interception mobile - capturez et maintenez les points.
- Kill loot creatures before they escape. -> Tuez les Gruzzlings avant qu'ils ne s'échappent avec le butin.
- Loot storage containers within time limit - beware of mimics. -> Certains conteneurs sont des mimiques déguisées.
- Special protoframe encounter - boss or sanctuary. -> Défendez la salle du Protoframe.
- Destroy Infested Tumors to eliminate their Hives. -> Défense - protégez la cible.
- Keep enemies out of a point, deposit offerings to spawn a boss. -> Défense de l'Autel - protégez l'autel.
- All enemies are Balloon-based Scaldura. -> Des ballons apparaissent dans l'arène.
- Loot storage containers. -> Butin de base.
- Blitz Leech. -> Des Liminus rapides drainent les PV et l'Énergie des alliés.
- All enemies are Rollers that leave behind a trail of fire. -> Des roulettes laissent des traînées de feu dans l'arène.
- Enemies are connected by flaming beams, burning players on contact. -> Des chaînes de feu relient les ennemis entre eux.
- Enemies are larger and slower than normal. -> Les ennemis sont plus grands et plus lents que la normale.
- Enemies are heavily resistant to all damage not dealt by Archguns or Rockets. -> Armes lourdes uniquement.
- Horse Combat Only. -> Combat à cheval uniquement.
- The player is forced to use Necramech against Rogue Necramechs. -> Combat de Necramech uniquement.
- Race through gates on a Kaithe. -> Course à cheval.
- Security Spin. -> Des lames tournantes se déplacent dans l'arène.
- Leech, Shock, or Venomous Eximus variant. -> Des Liminus électrifiés drainent les PV et l'Énergie des alliés.
- Debris is constantly falling from the ceiling, dealing damage to anyone caught underneath. -> Des plafonds à pointes descendent dans l'arène.
- Sunlight penance. -> La lumière du soleil inflige des dégâts aux ennemis.
- Infested Boyband. -> Des groupes d'ennemis Infestés arrivent en formation.
- Defeat Oraxia boss. -> Oraxia.
- Defeat a Sister of Parvos. -> Defeat a Sister of Parvos.
- Lyon's Sanctuary. -> Le Sanctuaire de Lyon.
"""
import json

LOCALES = ['de','es','it','ja','ko','pl','pt','ru','tc','th','tr','uk','zh']

# (en_value, [de, es, it, ja, ko, pl, pt, ru, tc, th, tr, uk, zh])
batch = [
    # en_value, locales
    ("Fill a Crucible using two elemental Amphors.",
     ["Füllen Sie einen Kessel mit zwei elementaren Amphors.",
      "Llena un crisol con dos Amphors elementales.",
      "Riempi un crostampe con due Amphors elementali.",
      "2つの元素アンフォーでクルシスルを満たします。",
      "두 개의 원소 앰포로 크루시블을 채웁니다.",
      "Napełnij piece dwoma elementalnymi Amphorami.",
      "Preencha um cadinho com dois Amphors elementais.",
      "Заполните кузну двумя стихийными Амфорами.",
      "使用兩個元素安佛充滿 crucible。",
      "ใส่ครูซิเบินด้วยองฆุมภ์สององค์",
      "İki elementalist Amphor kullanarak bir crucible doldur.",
      "Заповніть кузну двома стихійними Амфорами.",
      "使用两个元素安佛充满crucible。"]),
    ("Destroy floating hologlobes.",
     ["Zerstöre schwebende Hologlobes.",
      "Destruye hologlobos flotantes.",
      "Distruggi hologlobi galleggianti.",
      "浮遊するホログロブを破壊します。",
      "떠다니는 홀로글로브를 파괴합니다.",
      "Zniszcz unoszące się hologloby.",
      "Destruir hologlobos flutuantes.",
      "Разрушить плавающие гологлобы.",
      "摧毀浮動的全息體。",
      "ทำลายฮอล็อกอับที่ลอยอยู่",
      "Yüzen hologlopları yok et.",
      "Zniszcz unoszące się hologloby.",
      "摧毁浮动的全息体。"]),
    ("Capture the target.",
     ["Fassen Sie das Ziel.",
      "Captura el objetivo.",
      "Cattura l'obiettivo.",
      "目標を捕獲。",
      "목표를 포획한다.",
      "Schwyłów cel.",
      "Capture o alvo.",
      "Захватить цель.",
      "捕獲目標。",
      "จับเป้าหมาย",
      "Hedefi yakala.",
      "Schwyłów cel.",
      "捕获目标。"]),
    ("Collect Vitoplast.",
     ["Sammeln Sie Vitoplast.",
      "Recoge Vitoplast.",
      "Raccogli Vitoplast.",
      "Vitoplastを収集。",
      "비토플라스트 수집.",
      "Zbieraj Vitoplast.",
      "Colete Vitoplast.",
      "Собирать Витопласт.",
      "收集Vitoplast。",
      "เก็บ Vitoplast",
      "Vitoplast toplama.",
      "Zbieraj Vitoplast.",
      "收集Vitoplast。"]),
    ("Protect Excavators and keep them powered with Power Cells.",
     ["Schützen Sie Excavators und halten Sie sie mit Power Cells am Laufen.",
      "Protege los excavadoras y mantenlos alimentados con Power Cells.",
      "Proteggi gli scavi e tienili alimentati con Power Cells.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Chroń Kopacze i utrzymuj ich zasilanie Power Cells.",
      "Proteja escavatórios e mantenha-os alimentados com Power Cells.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Chroń Kopacze i utrzymuj ich zasilanie Power Cells.",
      "Chroń Kopacze i utrzymuj ich zasilanie Power Cells.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Kill a specific number of enemies.",
     ["Töten Sie eine bestimmte Anzahl von Feinden.",
      "Mata un número específico de enemigos.",
      "Uccidi un numero specifico di nemici.",
      "特定の数の敵を倒す。",
      "지정된 수의 적 죽이기.",
      "Zabij określoną liczbę wrogów.",
      "Mate um número específico de inimigos.",
      "Убить определённое количество врагов.",
      "殺死特定數量的敵人。",
      "ฆ่าจำนวนเฉพาะของศัตร์",
      "Belirli bir sayıda düşman öldür.",
      "Zabij określoną liczbę wrogów.",
      "杀死特定数量的敌人。"]),
    ("Cleanse nodes of Infestation to power a Vaporizer.",
     ["Reinigen Sie Knotenpunkte der Infektion, um einen Vaporizer zu betreiben.",
      "Limpia los nodos de la infestación para alimentar un vaporizador.",
      "Pulisci i nodi dell'infestazione per alimentare un vaporizzatore.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Oczyść węzły infestacji, aby zasilić parownik.",
      "Limpe os nós da infestação para alimentar um vaporizador.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Oczyść węzły infestacji, aby zasilić parownik.",
      "Oczyść węzły infestacji, aby zasilić parownik.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Defend and capture intercept points.",
     ["Verteidigen und fangen Sie Intercept-Punkte.",
      "Defiende y captura puntos de intercepción.",
      "Difendi e cattura punti di interferenza.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Chroń i zbieraj punkty przeciwdziałania.",
      "Defenda e capture pontos de interceptação.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Chroń i zbieraj punkty przeciwdziałania.",
      "Chroń i zbieraj punkty przeciwdziałania.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Kill loot creatures before they escape.",
     ["Töten Sie Beute-Kreaturen, bevor sie entkommen.",
      "Mata las criaturas de saqueo antes de que escapen.",
      "Uccidi le creature bottino prima che fuggano.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Zabij stworzenia łupów zanim ucieką.",
      "Mate as criaturas de saqueio antes que escapem.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Zabij stworzenia łupów zanim ucieką.",
      "Zabij stworzenia łupów zanim ucieką.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Loot storage containers within time limit - beware of mimics.",
     ["Plündern Sie Lagerbehälter innerhalb des Zeitlimits - passen Sie auf Mimics auf.",
      "Saqueo contenedores de almacenamiento dentro del límite de tiempo - cuidado con mimetismo.",
      "Bottino contenitori di stoccaggio entro il limite di tempo - attento alle mimetismo.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Zbieraj pojemniki składowe w określonym czasie - uważaj na kamuflaże.",
      "Colete contêineres de armazenamento dentro do limite de tempo - cuidado com mimetismo.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Zbieraj pojemniki składowe w określonym czasie - uważaj na kamuflaże.",
      "Zbieraj pojemniki składowe w określonym czasie - uważaj na kamuflaże.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Special protoframe encounter - boss or sanctuary.",
     ["Spezielle Protoframe-Begegnung - Boss oder Schrein.",
      "Encuentro protoframe especial - jefe o santuario.",
      "Incontro protoframe speciale - boss o santuario.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Specjalne spotkanie z protoframem - boss lub sanktuarium.",
      "Encontro protoframe especial - chefe ou santuário.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Specjalne spotkanie z protoframem - boss lub sanktuarium.",
      "Specjalne spotkanie z protoframem - boss lub sanktuarium.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Destroy Infested Tumors to eliminate their Hives.",
     ["Zerstören Sie Infested-Tumoren, um ihre Höhlen zu eliminieren.",
      "Destruye tumores infestados para eliminar sus colmenas.",
      "Distruggi i Tumori infetti per eliminare le loroarni.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Zniszcz Infested Noworyski na eliminację ich Kolczą.",
      "Destruir tumores infestados para eliminar suas colmeias.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Zniszcz Infested Noworyski na eliminację ich Kolczą.",
      "Zniszcz Infested Noworyski na eliminację ich Kolczą.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Keep enemies out of a point, deposit offerings to spawn a boss.",
     ["Halten Sie Feinde außerhalb eines Punktes, hinterlegen Sie Opfergaben, um einen Boss zu beschwören.",
      "Mantén a los enemigos fuera de un punto, deposita ofrendas para invocar un jefe.",
      "Tieni i nemici fuori punto, deposita offerte per far apparire un boss.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Trzymaj wrogów poza punktem, składaj ofiary na bossa.",
      "Mantenha os inimigos fora de um ponto, depositando oferendas para gerar um chefe.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Trzymaj wrogów poza punktem, składaj ofiary na bossa.",
      "Trzymaj wrogów poza punktem, składaj ofiary na bossa.",
      "Fill a Crucible using two elemental Amphors."]),
    ("All enemies are Balloon-based Scaldura.",
     ["Alle Feinde basieren auf Balloon-basierten Scaldura.",
      "Todos los enemigos son Scaldura basados en Balloon.",
      "Tutti i nemici sono Scaldura basati su Balloon.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Wszyscy wrogowie to Scaldura oparte na Balloon.",
      "Todos os inimigos são Scaldura baseado em Balloon.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Wszyscy wrogowie to Scaldura oparte na Balloon.",
      "Wszyscy wrogowie to Scaldura oparte na Balloon.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Loot storage containers.",
     ["Plündern Sie Lagerbehälter.",
      "Saqueo contenedores de almacenamiento.",
      "Bottino contenitori di stoccaggio.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Zbieraj pojemniki składowe.",
      "Colete contêineres de armazenamento.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Zbieraj pojemniki składowe.",
      "Zbieraj pojemniki składowe.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Blitz Leech.",
     ["Blitz Liminus.",
      "Blitz Liminus.",
      "Blitz Liminus.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Blitz Liminus.",
      "Blitz Liminus.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Blitz Liminus.",
      "Blitz Liminus.",
      "Fill a Crucible using two elemental Amphors."]),
    ("All enemies are Rollers that leave behind a trail of fire.",
     ["Alle Feinde sind Roller, die einen Feuerweg hinterlassen.",
      "Todos los enemigos son Rollers que dejan una estela de fuego.",
      "Tutti i nemici sono Roller che lasciano una scia di fuoco.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Wszyscy wrogowie to Rollerzy zostawiający ślad ognia.",
      "Todos os inimigos são Rollers que deixam uma trilha de fogo.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Wszyscy wrogowie to Rollerzy zostawiający ślad ognia.",
      "Wszyscy wrogowie to Rollerzy zostawiający ślad ognia.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Enemies are connected by flaming beams, burning players on contact.",
     ["Feinde sind durch flackernde Strahlen verbunden, die Spieler beim Kontakt verbrennen.",
      "Los enemigos están conectados por haces flamígentos que queman a los jugadores al contacto.",
      "I nemici sono collegati da raggi infuocati che bruciano i giocatori al contatto.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Wrogowie są połączeni przez ogniste wiązka, spalające graczy na kontakcie.",
      "Inimigos são conectados por feixes flamejantes que queimam os jogadores ao contato.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Wrogowie są połączeni przez ogniste wiązka, spalające graczy na kontakcie.",
      "Wrogowie są połączeni przez ogniste wiązka, spalające graczy na kontakcie.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Enemies are larger and slower than normal.",
     ["Feinde sind größer und langsamer als normal.",
      "Los enemigos son más grandes y más lentos que normal.",
      "I nemici sono più grandi e più lenti della norma.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Wrogowie są więksi i wolniejsi niż normalnie.",
      "Inimigos são maiores e mais lentos que o normal.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Wrogowie są więksi i wolniejsi niż normalnie.",
      "Wrogowie są więksi i wolniejsi niż normalnie.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Enemies are heavily resistant to all damage not dealt by Archguns or Rockets.",
     ["Feinde sind stark resistent gegen alle Schäden, die nicht durch Archguns oder Rockets verursacht werden.",
      "Los enemigos son muy resistentes a todos los daños no infligidos por Arcanás o Cohetes.",
      "I nemici sono fortemente resistenti a tutti i danni non inflitti da Archguns o Rockets.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Wrogowie są bardzo odporni na obrażenia niż nie wykonane przez Archguns lub Rockets.",
      "Inimigos são fortemente resistentes a todos os danos não infligidos por Archguns ou Rockets.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Wrogowie są bardzo odporni na obrażenia niż nie wykonane przez Archguns lub Rockets.",
      "Wrogowie są bardzo odporni na obrażenia niż nie wykonane przez Archguns lub Rockets.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Horse Combat Only.",
     ["Nur Pferde-Kampf.",
      "Combate a caballo solo.",
      "Combatti cavallo solo.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Tylko walka na koniu.",
      "Combate a cavalo apenas.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Tylko walka na koniu.",
      "Tylko walka na koniu.",
      "Fill a Crucible using two elemental Amphors."]),
    ("The player is forced to use Necramech against Rogue Necramechs.",
     ["Der Spieler ist gezwungen, Necramech gegen Rogue Necramechs zu verwenden.",
      "El jugador debe usar Necramech contra Necramechs rebeldes.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Gracz musi używać Necramech przeciw Rogue Necramechs.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Gracz musi używać Necramech przeciw Rogue Necramechs.",
      "Gracz musi używać Necramech przeciw Rogue Necramechs.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Race through gates on a Kaithe.",
     ["Rennen Sie durch Türmen auf einem Kaithe.",
      "Carrera a través de portadas en un Kaithe.",
      "Corsa attraverso porte su un Kaithe.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Wyścig przez bramy na Kaithe.",
      "Corra através de portais em um Kaithe.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Wyścig przez bramy na Kaithe.",
      "Wyścig przez bramy na Kaithe.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Security Spin.",
     ["Sicherheitsspin.",
      "Spin de seguridad.",
      "Spin di sicurezza.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Spin bezpieczeństwa.",
      "Spin de segurança.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Spin bezpieczeństwa.",
      "Spin bezpieczeństwa.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Leech, Shock, or Venomous Eximus variant.",
     ["Liminus, Shock oder Venomous Eximus Variante.",
      "Liminus, Shock o Shock variante de Eximus.",
      "Liminus, Shock o Shock variante di Eximus.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Liminus, Shock lub Venomous Eximus.",
      "Liminus, Shock ou Shock variante de Eximus.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Liminus, Shock lub Venomous Eximus.",
      "Liminus, Shock lub Venomous Eximus.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Debris is constantly falling from the ceiling, dealing damage to anyone caught underneath.",
     ["Trümmer fallen ständig vom Decken, was Schaden verursacht.",
      "Los escombros caen constantemente del techo, infligiendo daño a quien esté debajo.",
      "I detriti cadono continuamente dal soffitto, infliggendo danni a chi è sotto.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Odpadki stale spadają z sufitu, raniąc każdego, kto pod nimi.",
      "Os escombros caem constantemente do teto, causando dano a quem estiver embaixo.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Odpadki stale spadają z sufitu, raniąc każdego, kto pod nimi.",
      "Odpadki stale spadają z sufitu, raniąc każdego, kto pod nimi.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Sunlight penance.",
     ["Sonnenlicht-Buße.",
      "Penitencia al sol.",
      "Pena alla Luce del Sole.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Rozgrzeszenie Nasłonecznieniem.",
      "Penitência de Sol.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Rozgrzeszenie Nasłonecznieniem.",
      "Rozgrzeszenie Nasłonecznieniem.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Infested Boyband.",
     ["Infested Boyband.",
      "Boyband Infestado.",
      "Boyband Infetto.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Infested Boyband.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Infested Boyband.",
      "Infested Boyband.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Defeat Oraxia boss.",
     ["Oraxia Boss besiegen.",
      "Derrota al jefe Oraxia.",
      "Sconfiggi il boss Oraxia.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Pokonaj bossa Oraxia.",
      "Derrote o chefe Oraxia.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Pokonaj bossa Oraxia.",
      "Pokonaj bossa Oraxia.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Defeat a Sister of Parvos.",
     ["Besiege eine Schwester der Parvos.",
      "Derrota a una Hermana de Parvos.",
      "Sconfiggi una Sorella di Parvos.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Pokonaj Siostrę Parvos.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Pokonaj Siostrę Parvos.",
      "Pokonaj Siostrę Parvos.",
      "Fill a Crucible using two elemental Amphors."]),
    ("Lyon's Sanctuary.",
     ["Lyons Schrein.",
      "Santuario de Lyon.",
      "Santuario di Lyon.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Świątynia Lyona.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Fill a Crucible using two elemental Amphors.",
      "Świątynia Lyona.",
      "Świątynia Lyona.",
      "Fill a Crucible using two elemental Amphors."]),
]

batch_dict = {en_val: trans for en_val, trans in batch}
with open('translations_batch4.json', 'w', encoding='utf-8') as f:
    json.dump(batch_dict, f, ensure_ascii=False, indent=2)
print(f"Wrote {len(batch_dict)} entries to translations_batch4.json")
